### ISSUE TITLE
needed 'require'

### ISSUE THREAD

**Issue by fist28** [gocardless/activejob-retry#26]
To use this gem I had to add 'require `active_job/retry` in my job.

**Comment by isaacseymour** [comment]
Hi @fist28, you can get around this by doing:
```ruby
gem 'activejob-retry', '~> 0.4.0', require: 'active_job/retry'
```
in your gemfile, but it's kinda annoying. The problem is that `active_job-retry` is a well ugly gem name, but is the correct name for the module. I'm tempted to add a file at `lib/activejob/retry.rb` which requires `lib/active_job/retry.rb`, but it's kinda grim too :(

**Comment by isaacseymour** [comment]
#27 will resolve this

**Comment by isaacseymour** [comment]
@fist28 this is now pushed to RubyGems in 0.4.1 :)

**Comment by fist28** [comment]
thanks
