### ISSUE TITLE
resque-scheduler dependency

### ISSUE THREAD

**Issue by lewispb** [gocardless/activejob-retry#33]
Got an error, To be able to schedule jobs with Resque you need the resque-scheduler gem. Please add it to your Gemfile and run bundle install

Do you need to add it to gem spec? Thanks.

**Comment by isaacseymour** [comment]
Because ActiveJob wraps many queue libraries, it does not depend on any of them (otherwise you'd have to install Sidekiq, Que, etc, when you're only using Resque). ActiveJob-Retry does not have a runtime dependency on any one queue library for the same reason. You should add `resque-scheduler` to *your* Gemfile.

**Comment by lewispb** [comment]
Makes sense thanks.
